site_name: PER Caisse | Documentation
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: teal
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: lime

extra:
  social:
    - icon: fontawesome/brands/gitlab
      link: https://git.enib.fr/projet-ecoresponsable/projet-ecoresponsable_logiciel-de-caisse
    - icon: fontawesome/brands/google-drive
      link: https://drive.google.com/drive/u/0/folders/1dtXQ37407rYvrs2MbIS1YNGeehq2ksk_

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

copyright: |
  &copy; 2023 <a href="https://enib.fr"  target="_blank" rel="noopener">ENIB | Johnny SAGHBINI - Hassan SERHAN - Roy AL NABBOUT - Valentine BUQUET - Nagham AJINEH</a>